/*
 * Copyright (C) 2018 Elisa Rojas(1), Hedayat Hosseini(2), and David Carrascal(1);
 *                    (1) GIST, University of Alcala, Spain.
 *                    (2) CEIT, Amirkabir University of Technology (Tehran
 *                        Polytechnic), Iran.
 * To read and process the IoTorii log file generated in Contiki-ng
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#define NODE_NUMBERS_MAX 500
#define CONDITION_MAX 11
#define HLMAC_STR_LEN_MAX 20
#define GLOBAL_STATISTICS 1  //To print a metric for all runs in a file

int main(int argc, char *argv[])
{
    int log_file_parser(FILE *, char *);
    FILE *fp;
    char destfile[50] = "output_file_";

    printf("\nIoTorii log parser 2018\n\n");

    if (argc==1)
    {
        fprintf(stderr,"\nNo log file introduced\n");
    }
    else{
            if ((fp= fopen(*++argv,"r"))==NULL){
                fprintf(stderr,"\nCan't open %s\n",*argv);
                return 1;
            }else{
                strcat(destfile,*argv);
                if (log_file_parser(fp,destfile))
                    printf("\nNew files were generated successfully.\n");
                else
                    printf("\nNew files are not generated successfully! please try again.\n");
                fclose(fp);
            }

    }

    return 0;
}
/*---------------------------------------------------------------------------*/
int log_file_parser(FILE *fp, char *destfile){

    char line[200];
    int i,common_check=0,check_condition[CONDITION_MAX];

#if GLOBAL_STATISTICS == 1
    FILE *ConvergenceTime; //A file to save convergence time for all nodes
    if((ConvergenceTime=fopen("01_ConvergenceTime.txt","a"))==NULL){
       fprintf(stderr,"\nCan't open destination file (ConvergenceTime.txt)\n");
       return 0;

     }

     FILE *numberOfTableEntries;
     if((numberOfTableEntries=fopen("02_NumberOfTableEntries.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfTableEntries.txt)\n");
        return 0;

     }

     FILE *numberOfMessages;
     if((numberOfMessages=fopen("03_NumberOfMessages.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfMessages.txt)\n");
        return 0;

     }

     FILE *numberOfHops;
     if((numberOfHops=fopen("04_NumberOfHops.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfHops.txt)\n");
        return 0;

     }

     FILE *numberOfNeighbors;
     if((numberOfNeighbors=fopen("05_NumberOfNeighbors.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfNeighbors.txt)\n");
        return 0;

     }

     FILE *numberOfParents;
     if((numberOfParents=fopen("06_NumberOfParents.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfParents.txt)\n");
        return 0;

     }

     FILE *numberOfDefaultRoutes;
     if((numberOfDefaultRoutes=fopen("07_NumberOfDefaultRoutes.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfDefaultRoutes.txt)\n");
        return 0;

     }

     FILE *numberOfRoutes;
     if((numberOfRoutes=fopen("08_NumberOfRoutes.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfRoutes.txt)\n");
        return 0;

     }

     FILE *numberOfSREntries;
     if((numberOfSREntries=fopen("09_NumberOfSREntries.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfSREntries.txt)\n");
        return 0;

     }

     FILE *numberOfDISMessages;
     if((numberOfDISMessages=fopen("10_NumberOfDISMessages.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfDISMessages.txt)\n");
        return 0;

     }

     FILE *numberOfDIOMessages;
     if((numberOfDIOMessages=fopen("11_NumberOfDIOMessages.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfDIOMessages.txt)\n");
        return 0;

     }

     FILE *numberOfDAOMessages;
     if((numberOfDAOMessages=fopen("12_NumberOfDAOMessages.txt","a"))==NULL){
        fprintf(stderr,"\nCan't open destination file (NumberOfDAOMessages.txt)\n");
        return 0;

     }

#endif

    FILE *destfp;
    if((destfp=fopen(destfile,"w"))==NULL){
       fprintf(stderr,"\nCan't open destination file (%s)\n",destfile);
       return 0;

       }else{
           strcat(line,"** This file was generated by RPL log parser **\n\n");
           fputs(line,destfp);

           int node_id_max = 0;
           float convergence_time_end = 0;
           float convergence_time_start = 0;
           float convergence_time = 0;
           int number_of_neighbours[NODE_NUMBERS_MAX], number_of_parents[NODE_NUMBERS_MAX], number_of_default_routes[NODE_NUMBERS_MAX], number_of_routes[NODE_NUMBERS_MAX], number_of_sr_entries[NODE_NUMBERS_MAX];
           int number_of_dis_messages[NODE_NUMBERS_MAX], number_of_dio_messages[NODE_NUMBERS_MAX], number_of_dao_messages[NODE_NUMBERS_MAX];
           int number_of_table_entries[NODE_NUMBERS_MAX], number_of_messages[NODE_NUMBERS_MAX];
           //int sum_hop[NODE_NUMBERS_MAX];
           float average_sum_hop_for_node = 0;

           //Variables to calculate average
           float average_number_of_neighbours = 0, average_number_of_parents = 0, average_number_of_default_routes = 0, average_number_of_routes = 0, average_number_of_sr_entries = 0;
           float average_number_of_dis_messages = 0, average_number_of_dio_messages = 0, average_number_of_dao_messages = 0;
           float average_number_of_table_entries = 0, average_number_of_messages = 0;
           float average_sum_hop = 0;

           for (i=0; i<NODE_NUMBERS_MAX; i++){
             number_of_neighbours[i] = number_of_parents[i] = number_of_default_routes[i] = number_of_routes[i] = number_of_sr_entries[i] = 0;
             number_of_dis_messages[i] = number_of_dio_messages[i] = number_of_dao_messages[i] = 0;
             number_of_table_entries[i] = number_of_messages[i] = 0;
           }

           while ((fgets(line,200,fp)) && (convergence_time_end == 0)){
                for(i=0;i<CONDITION_MAX;i++)
                    check_condition[i]=0;

                common_check=(strstr(line,"Periodic Statistics:")) && 1; // || 1 to avoid warning because type of common_check is int and the type of strstr() is char *.
                check_condition[0] = common_check && (strstr(line,"DIS:"));
                check_condition[1] = common_check && (strstr(line,"DIO:"));
                check_condition[2] = common_check && (strstr(line,"DAO:"));

                check_condition[3] = common_check && (strstr(line,"convergence time started"));
                check_condition[4] = common_check && (strstr(line,"convergence time ended"));

                check_condition[5] = common_check && (strstr(line,"Neighbors:"));
                check_condition[6] = common_check && (strstr(line,"Parents:"));

                check_condition[7] = common_check && (strstr(line,"Default routes:"));
                check_condition[8] = common_check && (strstr(line,"Routes:"));

                check_condition[9] = common_check && (strstr(line,"Number of nodes:"));

                check_condition[10] = common_check && (strstr(line,"SR-Entries:"));


                if(check_condition[0]){ //Number of DIS
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"DIS:") + strlen("DIS:"), "%d", &number_of_dis_messages[node_id-1]);
                }

                if(check_condition[1]){ //Number of DIO
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"DIO:") + strlen("DIO:"), "%d", &number_of_dio_messages[node_id-1]);
                }
                if(check_condition[2]){ //Number of DAO
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"DAO:") + strlen("DAO:"), "%d", &number_of_dao_messages[node_id-1]);
                }

                if(check_condition[3]){ //convergence time started
                  int convergence_time_start_minute = 0;
                  float convergence_time_start_sec = 0;
                  sscanf(line, "%d:%f", &convergence_time_start_minute, &convergence_time_start_sec);
                  convergence_time_start = convergence_time_start_minute * 60 + convergence_time_start_sec;
                }

                if(check_condition[4]){ //convergence time ended
                  int convergence_time_end_minute;
                  float convergence_time_end_sec;
                  sscanf(line, "%d:%f", &convergence_time_end_minute, &convergence_time_end_sec);
                  convergence_time_end = convergence_time_end_minute * 60 + convergence_time_end_sec;
                }

                if(check_condition[5]){ //Neigbors
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"Neighbors:") + strlen("Neighbors:"), "%d", &number_of_neighbours[node_id-1]);
                }

                if(check_condition[6]){ //Parents
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"Parents:") + strlen("Parents:"), "%d", &number_of_parents[node_id-1]);
                }

                if(check_condition[7]){ //Default Routes
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"Default routes:") + strlen("Default routes:"), "%d", &number_of_default_routes[node_id-1]);
                }

                if(check_condition[8]){ //Routes
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"Routes:") + strlen("Routes:"), "%d", &number_of_routes[node_id-1]);
                }

                if(check_condition[9]){ //Number of nodes:
                  sscanf(strstr(line,"Number of nodes:") + strlen("Number of nodes:"), "%d", &node_id_max);
                }

                if(check_condition[10]){ //SR-Entries
                  int node_id;
                  sscanf(strstr(line,"M[") + strlen("M["), "%d", &node_id);
                  sscanf(strstr(line,"SR-Entries:") + strlen("SR-Entries:"), "%d", &number_of_sr_entries[node_id-1]);
                }

           }//END while
           fprintf(destfp, "Number of nodes:\t%d\n", node_id_max);

           fprintf(destfp, "convergence_time_start\t%f\t(s)\n", convergence_time_start);
           fprintf(destfp, "convergence_time_end\t%f\t(s)\n", convergence_time_end);

           convergence_time = convergence_time_end - convergence_time_start;
           fprintf(destfp, "convergence_time\t%f\t(s)\n", convergence_time);
           #if GLOBAL_STATISTICS == 1
           fprintf(ConvergenceTime, "%f\n", convergence_time);
           #endif
           fputs("---------------------------------------------------------------\n",destfp);

           fprintf(destfp, "node_id\tnumber_of_neighbours\tnumber_of_parents\tnumber_of_default_routes\tnumber_of_routes\tnumber_of_sr_entries\tnumber_of_table_entries");
           fprintf(destfp, "\tnumber_of_dis_messages\tnumber_of_dio_messages\tnumber_of_dao_messages\tnumber_of_messages\n");
           //fprintf(destfp, "\tsum_hop\taverage_sum_hop_for_node\n");
           int i;
           for (i=0; i<node_id_max; i++){
             number_of_table_entries[i] = number_of_neighbours[i] + number_of_parents[i] + number_of_default_routes[i] + number_of_routes[i] + number_of_sr_entries[i];
             number_of_messages[i] = number_of_dis_messages[i] + number_of_dio_messages[i] + number_of_dao_messages[i];
             fprintf(destfp, "%7d\t%20d\t%17d\t%24d\t%16d\t%20d\t%23d\t%22d\t%22d\t%22d\t%18d\n", i+1, number_of_neighbours[i], number_of_parents[i], number_of_default_routes[i], number_of_routes[i],number_of_sr_entries[i], number_of_table_entries[i], number_of_dis_messages[i], number_of_dio_messages[i], number_of_dao_messages[i], number_of_messages[i]);

             //Summation calculation
             average_number_of_neighbours += number_of_neighbours[i];
             average_number_of_parents += number_of_parents[i];
             average_number_of_default_routes += number_of_default_routes[i];
             average_number_of_routes += number_of_routes[i];
             average_number_of_sr_entries += number_of_sr_entries[i];
             average_number_of_table_entries += number_of_table_entries[i];

             average_number_of_dis_messages += number_of_dis_messages[i];
             average_number_of_dio_messages += number_of_dio_messages[i];
             average_number_of_dao_messages += number_of_dao_messages[i];
             average_number_of_messages += number_of_messages[i];
             //average_sum_hop += sum_hop[i];
           }
           fputs("---------------------------------------------------------------\n",destfp);

           fprintf(destfp, "Sum    \t%20f\t%17f\t%24f\t%16f\t%20f\t%23f\t%22f\t%22f\t%22f\t%18f\n", average_number_of_neighbours, average_number_of_parents, average_number_of_default_routes, average_number_of_routes, average_number_of_sr_entries, average_number_of_table_entries, average_number_of_dis_messages, average_number_of_dio_messages, average_number_of_dao_messages, average_number_of_messages);

           //Average calculation
           //average_sum_hop /= average_number_of_hlmac_addresses; //Now, average_number_of_hlmac_addresses includes the total number of the hlmac addresses
           average_number_of_neighbours /= node_id_max;
           average_number_of_parents /= node_id_max;
           average_number_of_default_routes /= node_id_max;
           average_number_of_routes /= node_id_max;
           average_number_of_table_entries /= node_id_max;

           average_number_of_dis_messages /= node_id_max;
           average_number_of_dio_messages /= node_id_max;
           average_number_of_dao_messages /= node_id_max;
           average_number_of_messages /= node_id_max;

           fprintf(destfp, "Average\t%20f\t%17f\t%24f\t%16f\t%20f\t%23f\t%22f\t%22f\t%22f\t%18f\n", average_number_of_neighbours, average_number_of_parents, average_number_of_default_routes, average_number_of_routes, average_number_of_sr_entries, average_number_of_table_entries, average_number_of_dis_messages, average_number_of_dio_messages, average_number_of_dao_messages, average_number_of_messages);

           #if GLOBAL_STATISTICS == 1
           fprintf(numberOfTableEntries, "%f\n", average_number_of_table_entries);
           fprintf(numberOfNeighbors, "%f\n", average_number_of_neighbours);
           fprintf(numberOfParents, "%f\n", average_number_of_parents);
           fprintf(numberOfDefaultRoutes, "%f\n", average_number_of_default_routes);
           fprintf(numberOfRoutes, "%f\n", average_number_of_routes);
           fprintf(numberOfSREntries, "%f\n", average_number_of_sr_entries);

           fprintf(numberOfMessages, "%f\n", average_number_of_messages);
           fprintf(numberOfDISMessages, "%f\n", average_number_of_dis_messages);
           fprintf(numberOfDIOMessages, "%f\n", average_number_of_dio_messages);
           fprintf(numberOfDAOMessages, "%f\n", average_number_of_dao_messages);
           #endif
           fputs("---------------------------------------------------------------\n",destfp);

           fclose(destfp);
           //fclose(numberOfHops);
           fclose(ConvergenceTime);
           fclose(numberOfTableEntries);
           fclose(numberOfNeighbors);
           fclose(numberOfParents);
           fclose(numberOfDefaultRoutes);
           fclose(numberOfRoutes);
           fclose(numberOfSREntries);
           fclose(numberOfMessages);
           fclose(numberOfDISMessages);
           fclose(numberOfDIOMessages);
           fclose(numberOfDAOMessages);

       }
       return 1;
}
